### ISSUE TITLE
Connection using DBAL

### ISSUE THREAD

**Issue by ghost** [voku/session2db#15]
How to use doctrine/dbal or nextras/dbal for connection in getInstance?

DB::getInstance('localhost', 'andy', 'andy', 'database'); 

I've try using doctrine  dbal but don't work!!!

**Comment by voku** [comment]
doc: https://github.com/voku/simple-mysqli#doctrinedbal-as-parent-driver
tests: https://github.com/voku/simple-mysqli/blob/master/tests/SimpleDoctrinePdoTest.php#L30

... I hope this documentation and code examples can help you. Happy coding! :)

**Comment by ghost** [comment]
Thanks man!!!
