### ISSUE TITLE
Loading without composer?

### ISSUE THREAD

**Issue by kimboslice99** [voku/session2db#18]
How? Not a fan of composer. Whats the right order to load these classes in?

```
 PHP Fatal error:  Uncaught Error: Interface "helper\Db4Session" not found 
```

Edit; even with composer im running into issues; I see its noted 
```
*Note that this class assumes that there is an active connection to a MySQL database and it does not attempt to create one!
```
Okay then, how is this class expecting the connection to be made? like $mysqli = new mysqli(); or?

**Comment by voku** [comment]
composer: Do whatever you want, but composer will make your (and the team) development experience much better. 🌌

mysqli: There is an example in the README and it is always a good idea to look into the tests (because there are working examples) and if you don't find the tests , you know you don't want to use it at all. 😉

**Comment by kimboslice99** [comment]
I just prefer to know whats being used and gain a better understanding of the library im using

<strike>After an entire day of fighting with this I've given up and started writing my own session handler, oh well</strike>

After much more effort I have managed to get it working! Curious, are there any plans to update to support PHP 8.1? I Believe theres some changes with return types in php 8.0? You're likely better educated here

<strike>Edit: seems using your second example gives me issues, session will not persist across pages. using just new Session2DB(); without params works as intended however?</strike>
 
**A session lifetime of 0 doesnt seem to have the expected result of a session that lasts until the browser is closed**, Line 180 of Session2DB.php makes it seem as though it should, it also says you can pass empty strings to keep default values, which doesnt seem to be the case?
