### ISSUE TITLE
PHP 7.1 Incompatible Change (INIs)

### ISSUE THREAD

**Issue by P-a-d-r-a-i-g** [voku/session2db#5]
According to [PHP 7.1 Incompatible Changes](http://php.net/manual/en/migration71.incompatible.php) the following INIs used in the `Session2DB` constructor are removed:

`session.hash_function`
`session.hash_bits_per_character`

**Comment by voku** [comment]
Thanks for the info! 👍 

fixed -> https://github.com/voku/session2db/commit/0e23f8d7e71c2ef7c5ad7a014d90f2ef34a18193
tests -> https://travis-ci.org/voku/session2db/builds/228383210

**Comment by P-a-d-r-a-i-g** [comment]
I don't think this will resolve it.

According to [PHP RFC: Session ID without hashing](https://wiki.php.net/rfc/session-id-without-hashing#implementation), the implementation has the following defaults due to backwards compatibility:

`session.sid_length=26`
`session.sid_bits_per_character=5`

Your previous `session.hash_function` value of 1 means SHA-1 (160 bits / 20 bytes) but this won't make a difference as the hashing function is replaced anyway. Also, you have `session_id varchar(32)` for the table.

Your previous `session.hash_bits_per_character` value of 6 would need to be applied to `session.sid_bits_per_character` instead as it defaults to 5.

**Comment by voku** [comment]
The new default settings from PHP are backwards compatible, so 32 chars is still working (see the tests at Travis-CI). But in the next major release, we can add breaking changes (BC) and we can increase the values... I will test it.

**Comment by P-a-d-r-a-i-g** [comment]
Ya, I meant that the number of characters will be fine for your current release, but the main part I want you to know about is that the bits per character will actually decrease from your original code with the default PHP 7.1 values. You have the following pre PHP 7.1 code that sets bits per character to 6, but that INI has been removed in PHP 7.1:

`// Increase character-range of the session ID to help prevent brute-force attacks
    ini_set('session.hash_bits_per_character', 6);`

The new PHP 7.1 default of `session.sid_bits_per_character` is 5, not 6 as you originally intended to help prevent brute force attacks.

So, what I'm saying is that you need to replace the pre PHP 7.1 code of `ini_set('session.hash_bits_per_character', 6)` with the new `session.sid_bits_per_character`. You have just an `if not PHP 7.1` statement around the original `ini_set` so this means the default of 5 bits per character will be used.

Hope this clarifies it.
