### ISSUE TITLE
Support for Galera Cluster

### ISSUE THREAD

**Issue by djschilling** [voku/session2db#6]
Galera Cluster has some limitations. One of them is not supporting `GET_LOCK` and `RELEASE_LOCK`.

From there website:

> Unsupported explicit locking include LOCK TABLES, FLUSH TABLES {explicit table list} WITH READ LOCK, (GET_LOCK(), RELEASE_LOCK(),…). Using transactions properly should be able to overcome these limitations. Global locking operators like FLUSH TABLES WITH READ LOCK are supported.
(https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/)

This prevents us from using session2db as a session-implementation at the moment.

Is there a plan to support Galera Cluster soon?

**Comment by voku** [comment]
Hi, in version 3.1.0 there is a public method called "use_lock_via_mysql(bool);" - if you set this option to "false", the lock-logic will use php instead of mysql. It's released some minutes ago, so the new feature isn't well tested, but the unit-tests are green and it's working on my local linux box.

**Comment by djschilling** [comment]
Thanks for the fast response.

I'm not sure this option will work for us.

Our setup looks like this:

We have three PHP-Servers where the users randomly hit one. And we have 3 Galera-Cluster Servers which are randomly used by the PHP-Servers for DB-Queries.

If i understand the `use_lock_via_mysql ` correct, it saves a file in the tmp folder of the server. So that will not work on our servers, because the lock file is then only on one of our servers. Is that correct, or am i misunderstanding this?

**Comment by voku** [comment]
Yep, you are correct ... 

In version 3.2.0 there is a second sql-table with lock-data + timestamp. You need the new sql-tabel from "/install/lock_data.sql" and you need to set the ```use_lock_via_mysql``` to ```null```.

**Comment by djschilling** [comment]
@voku Wow you are really quick.

I will try that out.

**Comment by djschilling** [comment]
I now tried this out and i had two problems wit it:

1. Using the method `use_lock_via_mysql`to set the behaviour to use mysql with extra lock table after creating the `Session2DB` instance seems to be to late. The session is already started in the instance creation of `Session2DB` and the session lock behaviour is the normal `RELEASE_LOCK` `GET_LOCK` thing. To configure it via constructor param should fix this.
Thats how i configured it:

```
    $session2DB = new Session2DB(
        '',
        $sessionLifetime,
        false,
        false,
        1,
        1000,
        'session_data',
        60,
        $dbWrapper
    );
    $session2DB->use_lock_via_mysql(null);
```

2. This is quite unrelated to the issue, but really important for me. I saw that you dropped support for PHP Version 5.6. I have to support PHP Version 5.6 and it would be really nice to get back the support for it in this lib so i can continue using it.

Thanks again for your support.

**Comment by djschilling** [comment]
@voku ^

**Comment by voku** [comment]
Hi, I have backported the changes from the "master"-branch into the "php_old"-branch and added version 2.1.0. 

There is a new parameter where you can skip the session_start and you can do it manually via Session2DB->start().

**Comment by djschilling** [comment]
Thanks for the work.
I tested the version 2.1.0 and it's not working for me.

Everytime i want to start the session it does not work.
I debugged it and found out that this line always returns false: https://github.com/voku/session2db/blob/php_old/src/voku/helper/Session2DB.php#L1221

This is how i configured it:

```
    $dbWrapper = new PDOMySQLSession();
    $session2DB = new Session2DB(
        '',
        $sessionLifetime,
        false,
        false,
        1,
        1000,
        'session_data',
        60,
        $dbWrapper,
        false
    );
    $session2DB->use_lock_via_mysql(null);
    $session2DB->start();
```

**Comment by voku** [comment]
have you enabled php-debugging via ...

```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

... maybe we can see the problem. And one more questions: how have you implemented the "ping()"-method in your "Db4Session"-class, because it is required to open the session.

**Comment by djschilling** [comment]
I found the problem.
```
Warning: session_set_save_handler() expects parameter 1 to be SessionHandlerInterface, object given in /Users/david/projects/churchtools/system/composer/voku/session2db/src/voku/helper/Session2DB.php on line 966
```
The class `Session2DB` needs to implement the interface `SessionHandlerInterface`.

**Comment by djschilling** [comment]
I adressed this issue and another that i encountered while testing with this pull request: #10

**Comment by voku** [comment]
I have added the interface also in the "php_old"-branch. It's tagged with version 2.1.1.

PS: Maybe it's not working for much older PHP versions e.g. PHP 5.3 but I think there is a polyfill from Symfony for this interface, so it should work (Travis-CI build is ok)

**Comment by djschilling** [comment]
Thanks for merging.

I only need PHP >= 5.6 so that should be fine.

**Comment by djschilling** [comment]
Version 2.1.2 is now working for me.

@voku Thanks for all the help.
